# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-25 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citas', '0001_initial'),
        ('clivet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clivet.Cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.Evento', verbose_name='Eventos frecuentes'),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
