# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clivet', '0003_auto_20161104_0522'),
        ('citas', '0002_auto_20161104_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clivet.Cliente'),
            preserve_default=False,
        ),
    ]
