# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
