# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20161010_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
