# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 22:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clivet', '0002_auto_20161027_2240'),
        ('citas', '0004_auto_20161011_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='motivo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='cita',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 27, 22, 39, 3, 985582, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.Evento', verbose_name='Eventos frecuentes'),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clivet.Trabajador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='color',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
