# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_auto_20161027_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
