# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_auto_20161027_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descripcion',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='title',
        ),
        migrations.AddField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='citas.Evento', verbose_name='Eventos frecuentes'),
            preserve_default=False,
        ),
    ]
