# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clivet', '0002_auto_20161027_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=300)),
                ('dx', models.CharField(max_length=300)),
                ('hallasgos_clinicos', models.CharField(max_length=100)),
                ('motivo_atencion', models.CharField(max_length=300)),
                ('observacion', models.CharField(max_length=300)),
                ('pronostico', models.CharField(max_length=300)),
                ('pruebas_auxiliares', models.CharField(max_length=300)),
                ('tratamiento', models.CharField(max_length=300)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('vobservacion', models.CharField(blank=True, max_length=100, null=True)),
                ('vacuna', models.CharField(blank=True, choices=[('VACUNA1', 'Vacuna1'), ('VACUNA2', 'Vacuna2'), ('VACUNA3', 'Vacuna3'), ('VACUNA4', 'Vacuna4')], max_length=100, null=True)),
                ('ndescripcion', models.CharField(blank=True, default='Mascota en buen estado', max_length=200, null=True)),
                ('created_ath', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creada')),
            ],
            options={
                'verbose_name_plural': 'Atenciones',
                'verbose_name': 'Atencion',
            },
        ),
        migrations.CreateModel(
            name='ColaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creada')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False, max_length=100, verbose_name='Estado de Atencion')),
            ],
            options={
                'verbose_name_plural': 'ColasMedicas',
                'verbose_name': 'ColaMedica',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=300)),
                ('dx', models.CharField(max_length=300)),
                ('hallasgos_clinicos', models.CharField(max_length=100)),
                ('motivo_atencion', models.CharField(max_length=300)),
                ('observacion', models.CharField(max_length=300)),
                ('pronostico', models.CharField(max_length=300)),
                ('pruebas_auxiliares', models.CharField(max_length=300)),
                ('tratamiento', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Consultas',
                'verbose_name': 'Consulta',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_historia', models.CharField(max_length=40)),
                ('created_ath', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creada')),
            ],
            options={
                'verbose_name_plural': 'Historias',
                'verbose_name': 'Historia',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('genero', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=10)),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Roedor', 'Roedor')], default='Perro', max_length=10)),
                ('raza', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('cond_corporal', models.CharField(choices=[('Buena', 'Buena'), ('Regular', 'Regular'), ('Demacrada', 'Demacrada')], default='Buena', max_length=10)),
                ('esterelizado', models.BooleanField(default=True, verbose_name='Esterelizado...?')),
                ('historia', models.BooleanField(default=False, verbose_name='Historia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_actived', models.BooleanField(default=False, verbose_name='Actived')),
                ('descripcion', models.CharField(max_length=200)),
                ('dueño', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='clivet.Cliente')),
            ],
            options={
                'verbose_name_plural': 'Mascotas',
                'verbose_name': 'Mascota',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndescripcion', models.CharField(default='Mascota en buen estado', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Notas',
                'verbose_name': 'Nota',
            },
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('Observacion', models.CharField(max_length=100)),
                ('vacuna', models.CharField(choices=[('VACUNA1', 'Vacuna1'), ('VACUNA2', 'Vacuna2'), ('VACUNA3', 'Vacuna3'), ('VACUNA4', 'Vacuna4')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Vacunaciones',
                'verbose_name': 'Vacunacion',
            },
        ),
        migrations.AddField(
            model_name='historial',
            name='mascota',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Mascota', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='historial',
            name='veterinario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clivet.Trabajador'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='mascota',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Mascota'),
        ),
        migrations.AddField(
            model_name='colamedica',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Historial'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='colamedica',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.ColaMedica', unique=True),
        ),
    ]
