# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-25 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0001_initial'),
        ('clivet', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clivet.Cliente'),
        ),
        migrations.AddField(
            model_name='historial',
            name='mascota',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Mascota', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='historial',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colamedica',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Historial'),
        ),
        migrations.AddField(
            model_name='colamedica',
            name='medico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atencion',
            name='colamedica',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.ColaMedica'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='diagnostico',
            field=models.ManyToManyField(max_length=300, to='clinica.Diagnostico'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='hallasgos_clinicos',
            field=models.ManyToManyField(max_length=300, to='clinica.HallasgosClinicos'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='pruebas_auxiliares',
            field=models.ManyToManyField(max_length=300, to='clinica.Pruebas'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='tratamiento',
            field=models.ManyToManyField(max_length=300, to='clinica.Tratamiento'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='vacuna',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='ventas.Producto'),
        ),
    ]
