# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clivet', '0001_initial'),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='clivet.Cliente'),
        ),
    ]
