# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clivet', '0001_initial'),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='clivet.Cliente'),
        ),
        migrations.AddField(
            model_name='historial',
            name='mascota',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Mascota'),
        ),
        migrations.AddField(
            model_name='historial',
            name='veterinario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clivet.Trabajador'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='mascota',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Mascota'),
        ),
        migrations.AddField(
            model_name='colamedica',
            name='historia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica.Historial'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='Vacunacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Vacunacion'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='colamedica',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.ColaMedica'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='consulta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Consulta'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='notas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Notas'),
        ),
    ]
