# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_historia', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('dueño', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.BooleanField()),
                ('raza', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('cond_corporal', models.CharField(choices=[('buena', 'Buena'), ('regular', 'Regular'), ('dema', 'Demacrada')], max_length=10)),
                ('esterelizado', models.BooleanField()),
                ('estado', models.BooleanField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='especie',
            old_name='color',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='raza',
        ),
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Especie'),
        ),
    ]
