# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='num_historia',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
