# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colamedica',
            options={'verbose_name': 'Cola Medica', 'verbose_name_plural': 'Colas Medicas'},
        ),
        migrations.AlterField(
            model_name='atencion',
            name='colamedica',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.ColaMedica'),
        ),
    ]
