# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20161009_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cond_corporal',
            field=models.CharField(choices=[('buena', 'Buena'), ('regular', 'Regular'), ('dema', 'Demacrada')], default='Buena', max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='clinica.Especie'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.BooleanField(choices=[('True', 'Vivo'), ('False', 'Fallecio')], default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='esterelizado',
            field=models.BooleanField(choices=[('1', 'Sí'), ('0', 'No')], default=True, verbose_name='Esterelizado...?'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.BooleanField(choices=[('1', 'Macho'), ('0', 'Hembra')], default='Macho', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='num_historia',
            field=models.CharField(max_length=10, verbose_name='N° Historia'),
        ),
    ]
