# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20161023_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colamedica',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creada'),
        ),
    ]
