# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20161025_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='colamedica',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.ColaMedica', unique=True),
        ),
    ]
