# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20161121_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notas',
        ),
        migrations.DeleteModel(
            name='Vacunacion',
        ),
        migrations.AlterField(
            model_name='historial',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
