# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20161024_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='esterelizado',
            field=models.BooleanField(default=True, verbose_name='Esterelizado...?'),
        ),
    ]
