# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clivet', '0001_initial'),
        ('clinica', '0002_mascota_dueño'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('emergencia', 'Emergencia'), ('reservado', 'Reservado')], max_length=100)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clivet.Cliente')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Mascota')),
            ],
            options={
                'verbose_name_plural': 'Colas Medicas',
                'verbose_name': 'Cola Medica',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=300)),
                ('dx', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField()),
                ('hallasgos_clinicos', models.CharField(max_length=100)),
                ('motivo_atencion', models.CharField(max_length=300)),
                ('observacion', models.CharField(max_length=300)),
                ('pronostico', models.CharField(max_length=300)),
                ('pruebas_auxiliares', models.CharField(max_length=300)),
                ('tratamiento', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Consultas',
                'verbose_name': 'Consulta',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Notas',
                'verbose_name': 'Nota',
            },
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('Observacion', models.CharField(max_length=100)),
                ('vacuna', models.CharField(choices=[('VACUNA1', 'Vacuna1'), ('VACUNA2', 'Vacuna2'), ('VACUNA3', 'Vacuna3'), ('VACUNA4', 'Vacuna4')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Vacunaciones',
                'verbose_name': 'Vacunacion',
            },
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
    ]
