# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clivet', '0001_initial'),
        ('clinica', '0003_auto_20161019_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_historia', models.CharField(max_length=40)),
                ('created_ath', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creada')),
                ('propietario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clivet.Cliente')),
                ('veterinario', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clivet.Trabajador')),
            ],
            options={
                'verbose_name_plural': 'Historias',
                'verbose_name': 'Historia',
            },
        ),
        migrations.AlterModelOptions(
            name='colamedica',
            options={'verbose_name': 'ColaMedica', 'verbose_name_plural': 'ColasMedicas'},
        ),
    ]
