# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        ('clinica', '0003_auto_20161104_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='atencion',
            name='vacuna',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='ventas.Producto'),
        ),
        migrations.RemoveField(
            model_name='colamedica',
            name='historia',
        ),
        migrations.AddField(
            model_name='colamedica',
            name='historia',
            field=models.ManyToManyField(blank=True, to='clinica.Historial'),
        ),
    ]
