# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20161115_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='diagnostico',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, to='clinica.Diagnostico'),
        ),
    ]
