# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20161009_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='cond_corporal',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Regular', 'Regular'), ('Demacrada', 'Demacrada')], default='Buena', max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('Vivo', 'Vivo'), ('Fallecio', 'Fallecio')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='esterelizado',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default=True, max_length=10, verbose_name='Esterelizado...?'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=10),
        ),
    ]
