# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20161024_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
    ]
