# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20161023_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='mascota',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='clinica.Mascota'),
        ),
    ]
