# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_auto_20161115_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='atencion',
            name='diagnostico',
            field=models.ManyToManyField(max_length=300, to='clinica.Diagnostico'),
        ),
    ]
