# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_auto_20161009_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
    ]
