# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_auto_20161104_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colamedica',
            name='historia',
        ),
        migrations.AddField(
            model_name='colamedica',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinica.Historial'),
            preserve_default=False,
        ),
    ]
