# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_auto_20161115_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='hallasgos_clinicos',
        ),
        migrations.AddField(
            model_name='atencion',
            name='hallasgos_clinicos',
            field=models.ManyToManyField(max_length=300, to='clinica.HallasgosClinicos'),
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='pruebas_auxiliares',
        ),
        migrations.AddField(
            model_name='atencion',
            name='pruebas_auxiliares',
            field=models.ManyToManyField(max_length=300, to='clinica.Pruebas'),
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='atencion',
            name='tratamiento',
            field=models.ManyToManyField(max_length=300, to='clinica.Tratamiento'),
        ),
    ]
