# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_auto_20161104_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colamedica',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Creada'),
        ),
    ]
