# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_auto_20161023_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='fecha',
        ),
    ]
