# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_auto_20161115_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='atencion',
            name='tratamiento',
            field=models.ForeignKey(default=1, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='clinica.Tratamiento'),
            preserve_default=False,
        ),
    ]
