# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_remove_consulta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='estado',
        ),
        migrations.AddField(
            model_name='mascota',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='is_actived',
            field=models.BooleanField(default=False, verbose_name='Actived'),
        ),
    ]
