# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_auto_20161115_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='atencion',
            name='tratamiento',
            field=models.ManyToManyField(max_length=300, to='clinica.Tratamiento'),
        ),
    ]
