# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_auto_20161107_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colamedica',
            name='veterinarios',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
