# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_auto_20161115_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='atencion',
            name='vacuna',
            field=models.CharField(blank=True, choices=[('consulta', 'Consulta General'), ('vacuna', 'Aplicar Vacuna'), ('antiparasitario', 'Aplicar Antiparasitario'), ('antipulgas', 'Aplicar Antipulga')], max_length=100, null=True),
        ),
    ]
