# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_auto_20161107_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colamedica',
            old_name='veterinarios',
            new_name='medico',
        ),
    ]
