# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 10:12
from __future__ import unicode_literals

import apps.ventas.models.Producto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_auto_20161115_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='atencion',
            name='tratamiento',
            field=models.CharField(choices=[('consulta', 'Consulta General'), ('vacuna', 'Aplicar Vacuna'), ('antiparasitario', 'Aplicar Antiparasitario'), ('antipulgas', 'Aplicar Antipulga')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atencion',
            name='vacuna',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=apps.ventas.models.Producto.Producto),
        ),
    ]
