# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_auto_20161020_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colamedica',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Historial'),
        ),
    ]
