# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20161109_1844'),
        ('clinica', '0011_auto_20161115_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='atencion',
            name='vacuna',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='ventas.Producto'),
        ),
    ]
