# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_auto_20161020_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='Vacunacion',
            new_name='vacunacion',
        ),
    ]
