# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_auto_20161115_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='Aptitup',
            field=models.CharField(blank=True, choices=[('compañia', 'Compañia'), ('guardia', 'Guardia'), ('trabajo', 'Trabajo'), ('deporte', 'Deporte'), ('casa', 'Casa')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='actividad',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='alimentacion',
            field=models.CharField(blank=True, choices=[('balanceada', 'Balanceada seca'), ('lata', 'Lata'), ('casera', 'Casera'), ('huevos', 'Huevos'), ('huevos', 'Otros')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='caracter',
            field=models.CharField(blank=True, choices=[('tranquilo', 'Tranquilo'), ('agresivo', 'Agresivo'), ('nervioso', 'Nervioso')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='convive',
            field=models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='habitar',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('azotea', 'Azotea'), ('campo', 'Campo'), ('patio', 'Patio'), ('criadero', 'Criadero'), ('jardin', 'Jardin'), ('calle', 'Calle')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clivet.Cliente'),
        ),
    ]
