# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_auto_20161108_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colamedica',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinica.Historial'),
            preserve_default=False,
        ),
    ]
