# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_auto_20161118_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='Aptitup',
            new_name='aptitup',
        ),
    ]
