# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3, verbose_name='Número')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Tipos Documentos Identidad',
                'verbose_name': 'Tipo Documenento Identidad',
            },
        ),
    ]
