# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20161104_0522'),
        ('clinica', '0002_auto_20161104_0522'),
        ('clivet', '0002_auto_20161027_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
