# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodoc', models.CharField(max_length=30)),
                ('numdoc', models.IntegerField(max_length=30)),
                ('razon_social', models.CharField(max_length=50)),
                ('representante_legal', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=30)),
                ('enti_bancaria', models.CharField(max_length=30)),
                ('num_cuenta', models.IntegerField(max_length=30)),
                ('estado', models.BooleanField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'verbose_name': 'Proveedor',
            },
        ),
    ]
