# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipodoc',
            field=models.CharField(choices=[('DNI', 'Registro Unico de Comprobante'), ('RUC', 'Documento nacional de Identidad')], max_length=30),
        ),
    ]
