# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20161010_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='apellidos',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=30, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='enti_bancaria',
            field=models.CharField(max_length=30, verbose_name='Entidad bancaria'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='num_cuenta',
            field=models.IntegerField(max_length=30, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numdoc',
            field=models.IntegerField(max_length=30, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(max_length=50, verbose_name='Razon social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='representante_legal',
            field=models.CharField(max_length=50, verbose_name='Representante legal'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(max_length=9, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipodoc',
            field=models.CharField(choices=[('RUC', 'Registro Unico de Comprobante'), ('DNI', 'Documento nacional de Identidad')], max_length=30, verbose_name='Tipo de Documento'),
        ),
    ]
