# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-23 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20161111_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='enti_bancaria',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Entidad bancaria'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='representante_legal',
            field=models.CharField(max_length=50, verbose_name='Representante legal'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=9, null=True, verbose_name='Telefono'),
        ),
    ]
