# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20161123_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comprobante',
            field=models.ImageField(upload_to='comprobante_compra', verbose_name='Seleccione el archivo'),
        ),
    ]
