# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clivet', '0002_auto_20161027_2240'),
        ('compras', '0006_auto_20161010_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('comprobante', models.FileField(upload_to='comprobante_compra', verbose_name='Seleccione el archivo')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedor')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clivet.Trabajador')),
            ],
            options={
                'verbose_name_plural': 'Compras',
                'verbose_name': 'Compra',
            },
        ),
    ]
