# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_detalle_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
    ]
