# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        ('compras', '0009_auto_20161031_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio Total')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Producto')),
            ],
            options={
                'verbose_name_plural': 'Detalles Compra',
                'verbose_name': 'Detalle Compra',
            },
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Detalle_Compra',
        ),
    ]
