# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-23 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0003_auto_20160925_2342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([]),
        ),
    ]
