# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-08 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
