# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 21:00
from __future__ import unicode_literals

import apps.ventas.models.Categoria
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='MontoReal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Real'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=apps.ventas.models.Categoria.Categoria, to='ventas.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(verbose_name='Cantidad de Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaVencimiento',
            field=models.DateField(verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='igv',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IGV'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioC',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioV',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidadMedidaC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='ventas.UnidadMedida', verbose_name='Unidad de medida de Compras'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidadMedidaV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.UnidadMedida', verbose_name='Unidad de medida de Ventas'),
        ),
    ]
