# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-31 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='fechaV',
            new_name='fechav',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id',
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo',
            field=models.CharField(default=-12, max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
