# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='igv',
        ),
        migrations.AddField(
            model_name='venta',
            name='igv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
