# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20161108_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='El codigo debe ser lalala', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidadMedidaC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='ventas.UnidadMedida', verbose_name='U. medida de compras'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidadMedidaV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.UnidadMedida', verbose_name='U. medida para ventas'),
        ),
    ]
