# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20161104_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='MontoReal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Real'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(default=0.0, verbose_name='Cantidad de Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IGV'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fechav',
            field=models.DateField(auto_now_add=True),
        ),
    ]
