# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20161111_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='unidadMedidaC',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidadMedidaV',
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida_cv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_de_medidas', to='ventas.UnidadMedida', verbose_name='U. medida compra a ventas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='cant_equivalencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de equivalencia'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.UnidadMedida', verbose_name='Conversion'),
        ),
    ]
