# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20161111_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedidaC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('simbolo', models.CharField(max_length=10)),
                ('cant_equivalencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de equivalencia')),
            ],
            options={
                'verbose_name_plural': 'Unidad de medidas Compras',
                'verbose_name': 'Unidad de medida Compra',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedidaV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('simbolo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Unidad de medidas Ventas',
                'verbose_name': 'Unidad de medida Venta',
            },
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='conversion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida_cv',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
        migrations.AddField(
            model_name='unidadmedidac',
            name='unidad_medida_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.UnidadMedidaV', verbose_name='Unidad de medida para ventas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_de_medida', to='ventas.UnidadMedidaC', verbose_name='U. medida compra a ventas'),
            preserve_default=False,
        ),
    ]
