# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20161111_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedidac',
            name='cant_equivalencia',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cantidad de equivalencia'),
        ),
    ]
